// Recurring PR generation (spec §5) + Service Agreement expiry (spec §3.2).
// The one piece of the Service Agreement feature with no existing
// scheduler/cron anywhere in this codebase to model after — see
// backend-stpl/docs/service-agreement-approval-po-spec.md §5 and
// sql/13_recurring_pr_job.sql for the fuller design writeup. In-process
// interval timer rather than a cron dependency: the actual "is today a
// billing boundary" logic lives in SQL
// (sp_nt_GetAgreementsDueForRecurringPR), so this file only needs to poll
// periodically and stays correct even if it fires more or less often than
// exactly once a day.
import ServiceAgreementRepository from "../repository/ServiceAgreement.repository.js";
import PRService from "../../PR/services/PR.service.js";

const repo = new ServiceAgreementRepository();

const SWEEP_INTERVAL_MS = Number(process.env.RECURRING_PR_SWEEP_INTERVAL_MS) || 60 * 60 * 1000; // hourly
const STARTUP_DELAY_MS = 10_000;

function todayIso() {
  return new Date().toISOString().slice(0, 10);
}

// Reuses PRService.createPrRecords() — the exact same path a manual PR
// submission uses — so a recurring PR gets the §4.1 agreement-validation and
// server-side rate override for free, and is otherwise indistinguishable
// from a hand-submitted PR in pr_basic_info/pr_item_details.
//
// created_by is deliberately not set here: usp_InsertPurchaseRequest
// currently hardcodes @created_by = 'KTM1148' regardless of what's in the
// JSON payload (a pre-existing quirk noted in its own file, not something
// this job introduces or should silently work around) — so every PR, manual
// or recurring, is attributed the same way today. The `purpose` field is the
// only reliable way to tell a job-generated PR apart until that's fixed.
async function generatePrForAgreement(agreement, priority_sno) {
  const log_sno = await repo.reserveRecurringPRSlot(agreement.agreement_sno, agreement.billing_period_start);
  if (log_sno === null) return; // another process already claimed this exact period

  try {
    const payload = {
      basicInfo: {
        com_sno: agreement.com_sno,
        div_sno: agreement.div_sno,
        brn_sno: agreement.brn_sno,
        dept_sno: agreement.dept_sno,
        req_date: todayIso(),
        required_date: todayIso(),
        priority_sno,
        purpose: `Recurring: ${agreement.service_name} — ${agreement.agreement_no}`,
      },
      // No qty/unit_sno/est_cost/total_cost — usp_InsertPurchaseRequest v3
      // (sql/12_pr_agreement_autofill.sql) already defaults qty to 1 and
      // sources unit/rate from the agreement for any FIXED_RECURRING line
      // carrying a valid agreement_sno, exactly like a manually-built line
      // auto-filled via §4 would.
      items: [
        {
          service_sno: agreement.service_sno,
          agreement_sno: agreement.agreement_sno,
          item_type: "service",
          remarks: "Auto-generated by the recurring service billing job",
        },
      ],
    };

    const result = await PRService.createPrRecords(payload);
    await repo.finalizeRecurringPRLog(log_sno, { status: "CREATED", pr_no: result?.pr_no });
  } catch (error) {
    console.error(
      `Recurring PR generation failed for agreement ${agreement.agreement_no} (#${agreement.agreement_sno}):`,
      error.message
    );
    await repo.finalizeRecurringPRLog(log_sno, { status: "FAILED", error_message: String(error.message).slice(0, 500) });
  }
}

async function runRecurringPRSweep() {
  let due;
  try {
    due = await repo.getAgreementsDueForRecurringPR();
  } catch (error) {
    console.error("Recurring PR sweep: failed to fetch due agreements:", error.message);
    return;
  }
  if (!due.length) return;

  // Resolved once per sweep, not per agreement — a recurring PR has no human
  // picking a priority, so every job-generated PR gets whatever comes back
  // first from the existing priority list.
  const priority_sno = await repo.getDefaultPrioritySno().catch(() => null);

  for (const agreement of due) {
    // One bad agreement (misconfigured scope, missing workflow, etc.) must
    // not stop the rest of the batch — generatePrForAgreement already
    // catches and logs per-agreement, this loop just keeps going regardless.
    await generatePrForAgreement(agreement, priority_sno);
  }
}

async function runAgreementExpirySweep() {
  try {
    const expiredCount = await repo.expireServiceAgreements();
    if (expiredCount > 0) {
      console.log(`Service agreement expiry sweep: flipped ${expiredCount} agreement(s) to Expired.`);
    }
  } catch (error) {
    console.error("Service agreement expiry sweep failed:", error.message);
  }
}

function startServiceAgreementScheduledJobs() {
  const sweep = () => {
    runRecurringPRSweep().catch((error) => console.error("Recurring PR sweep crashed:", error.message));
    runAgreementExpirySweep().catch((error) => console.error("Agreement expiry sweep crashed:", error.message));
  };

  setTimeout(sweep, STARTUP_DELAY_MS);
  setInterval(sweep, SWEEP_INTERVAL_MS);
}

export { startServiceAgreementScheduledJobs, runRecurringPRSweep, runAgreementExpirySweep };
