-- ============================================================
-- Stored Procedure : sp_nt_CreatePOFromQuotation
-- Database         : Non_Trade (MSSQL)
-- Purpose          : Persist a Purchase Order generated by the Purchase
--                     Team from a selected supplier quotation.
--
-- The frontend (PurchaseTeamPage.handleCreatePO) already splits multi-group
-- POs into one call per split group, so this procedure only ever creates a
-- single po_request_info row (+ its items) per invocation — unlike
-- sp_Save_PO_Request, which loops over split groups itself.
--
-- @jsonInput keys (all from PurchaseTeamController.createPOFromQuotation):
--   pr_basic_sno, sq_basic_sno, vendor_sno, com_sno, div_sno, brn_sno,
--   dept_sno, budget_sno, budget_code, priority_sno, po_date, required_date,
--   purpose, terms_conditions, delivery_address, split_pr_no (optional),
--   created_by, items: [{ pr_item_sno, prod_sno, prod_name, specification,
--     qty, unit, unit_name, unit_price, discount_pct, tax_pct,
--     total_amount, remarks }]
--
-- Returns: po_basic_sno, po_no, pr_no, vendor_sno, result ('SUCCESS'|'FAILED')
-- ============================================================

IF OBJECT_ID('dbo.sp_nt_CreatePOFromQuotation', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_nt_CreatePOFromQuotation;
GO

CREATE PROCEDURE dbo.sp_nt_CreatePOFromQuotation
    @jsonInput NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @pr_basic_sno       INT            = CAST(JSON_VALUE(@jsonInput, '$.pr_basic_sno') AS INT);
        DECLARE @vendor_sno         INT            = CAST(JSON_VALUE(@jsonInput, '$.vendor_sno') AS INT);
        DECLARE @com_sno            INT            = CAST(JSON_VALUE(@jsonInput, '$.com_sno') AS INT);
        DECLARE @div_sno            INT            = CAST(JSON_VALUE(@jsonInput, '$.div_sno') AS INT);
        DECLARE @brn_sno            INT            = CAST(JSON_VALUE(@jsonInput, '$.brn_sno') AS INT);
        DECLARE @dept_sno           INT            = CAST(JSON_VALUE(@jsonInput, '$.dept_sno') AS INT);
        DECLARE @budget_sno         INT            = CAST(JSON_VALUE(@jsonInput, '$.budget_sno') AS INT);
        DECLARE @budget_code        VARCHAR(20)    = LEFT(ISNULL(JSON_VALUE(@jsonInput, '$.budget_code'), ''), 20);
        DECLARE @priority_sno       INT            = CAST(JSON_VALUE(@jsonInput, '$.priority_sno') AS INT);
        DECLARE @po_date            DATE           = ISNULL(TRY_CAST(JSON_VALUE(@jsonInput, '$.po_date') AS DATE), CAST(GETDATE() AS DATE));
        DECLARE @required_date      DATE           = TRY_CAST(JSON_VALUE(@jsonInput, '$.required_date') AS DATE);
        DECLARE @purpose            VARCHAR(200)   = LEFT(ISNULL(JSON_VALUE(@jsonInput, '$.purpose'), ''), 200);
        DECLARE @terms_conditions   VARCHAR(MAX)   = JSON_VALUE(@jsonInput, '$.terms_conditions');
        DECLARE @delivery_address   VARCHAR(500)   = LEFT(ISNULL(JSON_VALUE(@jsonInput, '$.delivery_address'), ''), 500);
        DECLARE @split_pr_no        NVARCHAR(30)   = JSON_VALUE(@jsonInput, '$.split_pr_no');
        DECLARE @created_by         VARCHAR(20)    = JSON_VALUE(@jsonInput, '$.created_by');

        IF @pr_basic_sno IS NULL OR @vendor_sno IS NULL
            THROW 51001, 'pr_basic_sno and vendor_sno are required.', 1;

        DECLARE @pr_no VARCHAR(30);
        SELECT @pr_no = pr_no FROM pr_basic_info WHERE pr_basic_sno = @pr_basic_sno;
        IF @pr_no IS NULL
            THROW 51002, 'pr_no not found in pr_basic_info for given pr_basic_sno.', 1;

        IF @split_pr_no IS NULL SET @split_pr_no = @pr_no;

        IF NOT EXISTS (SELECT 1 FROM OPENJSON(@jsonInput, '$.items'))
            THROW 51003, 'No items found in JSON.', 1;

        INSERT INTO po_request_info (
            vendor_sno, brn_sno, dept_sno, com_sno, div_sno,
            budget_sno, budget_code, pr_basic_sno,
            po_date, required_date,
            priority_sno, purpose, terms_conditions, delivery_address,
            is_active, workflow_types_id, current_approver_id,
            status, po_df_no, split_pr_no
        )
        VALUES (
            @vendor_sno, @brn_sno, @dept_sno, @com_sno, @div_sno,
            @budget_sno, @budget_code, @pr_basic_sno,
            @po_date, @required_date,
            @priority_sno, @purpose, @terms_conditions, @delivery_address,
            'Y', 0, '0',
            'A', NULL, @split_pr_no
        );

        DECLARE @po_basic_sno INT = SCOPE_IDENTITY();
        DECLARE @po_no VARCHAR(30) = 'PO-' + CAST(YEAR(@po_date) AS VARCHAR(4)) + '-' + RIGHT('0000' + CAST(@po_basic_sno AS VARCHAR(10)), 4);

        UPDATE po_request_info SET po_df_no = @po_no WHERE po_basic_sno = @po_basic_sno;

        INSERT INTO po_item_details (
            po_basic_sno, pr_item_sno, prod_sno, prod_name,
            budget_sno, specification,
            qty, unit, unit_name,
            agreed_unit_price, total_cost,
            discount_pct, tax_pct, net_cost,
            remarks,
            created_by, created_date,
            is_active, split_pr_no
        )
        SELECT
            @po_basic_sno,
            TRY_CAST(JSON_VALUE(item.value, '$.pr_item_sno') AS INT),
            TRY_CAST(JSON_VALUE(item.value, '$.prod_sno') AS INT),
            LEFT(JSON_VALUE(item.value, '$.prod_name'), 200),
            @budget_sno,
            LEFT(ISNULL(JSON_VALUE(item.value, '$.specification'), ''), 200),
            TRY_CAST(JSON_VALUE(item.value, '$.qty') AS DECIMAL(18,4)),
            TRY_CAST(JSON_VALUE(item.value, '$.unit') AS INT),
            LEFT(JSON_VALUE(item.value, '$.unit_name'), 200),
            TRY_CAST(JSON_VALUE(item.value, '$.unit_price') AS DECIMAL(18,4)),
            ISNULL(TRY_CAST(JSON_VALUE(item.value, '$.qty') AS DECIMAL(18,4)), 0)
                * ISNULL(TRY_CAST(JSON_VALUE(item.value, '$.unit_price') AS DECIMAL(18,4)), 0),
            ISNULL(TRY_CAST(JSON_VALUE(item.value, '$.discount_pct') AS DECIMAL(18,4)), 0),
            ISNULL(TRY_CAST(JSON_VALUE(item.value, '$.tax_pct') AS DECIMAL(18,4)), 0),
            ISNULL(TRY_CAST(JSON_VALUE(item.value, '$.total_amount') AS DECIMAL(18,4)),
                   ISNULL(TRY_CAST(JSON_VALUE(item.value, '$.qty') AS DECIMAL(18,4)), 0)
                       * ISNULL(TRY_CAST(JSON_VALUE(item.value, '$.unit_price') AS DECIMAL(18,4)), 0)),
            LEFT(ISNULL(JSON_VALUE(item.value, '$.remarks'), ''), 200),
            @created_by, GETDATE(),
            'Y', @split_pr_no
        FROM OPENJSON(@jsonInput, '$.items') AS item;

        COMMIT TRANSACTION;

        SELECT
            @po_basic_sno AS po_basic_sno,
            @po_no        AS po_no,
            @pr_no        AS pr_no,
            @vendor_sno   AS vendor_sno,
            'SUCCESS'     AS result;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

        SELECT
            ERROR_NUMBER()  AS ErrorNumber,
            ERROR_MESSAGE() AS ErrorMessage,
            ERROR_LINE()    AS ErrorLine,
            'FAILED'        AS result;
    END CATCH
END
GO
