-- sql/90_service_po_download_pdf.sql
-- Adds a downloadable-PDF-ready payload to sp_nt_ApproveServicePoCycle's
-- final-approval response (one entry per PO raised this cycle — usually one,
-- or one per supplier on a multi-supplier split, see sql/88). Shape mirrors
-- sp_nt_ApproveSupplierQuotation's po_header/vendor/po_items so the frontend
-- can reuse the existing Purchase Order PDF renderer
-- (utils/generatePOApprovalPdf.ts) unchanged for Service PO too.
-- Generated by build90.cjs from the LIVE definition — see
-- [[project-service-agreement-workflow]] memory for the technique.

CREATE OR ALTER PROCEDURE dbo.sp_nt_ApproveServicePoCycle
    @jsonInput NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        IF ISJSON(@jsonInput) = 0
        BEGIN
            RAISERROR('Invalid JSON format for @jsonInput', 16, 1);
            RETURN;
        END

        DECLARE @cycle_sno       INT           = TRY_CAST(JSON_VALUE(@jsonInput, '$.cycle_sno') AS INT),
                @comments        VARCHAR(200)  = JSON_VALUE(@jsonInput, '$.comments'),
                @approval_stages NVARCHAR(MAX) = JSON_QUERY(@jsonInput, '$.approval_stages'),
                @approved_by     VARCHAR(30)   = JSON_VALUE(@jsonInput, '$.approved_by'),
                @action          VARCHAR(30)   = JSON_VALUE(@jsonInput, '$.action');

        IF @cycle_sno IS NULL
        BEGIN
            RAISERROR('cycle_sno is required.', 16, 1);
            RETURN;
        END

        IF @action IS NULL OR LTRIM(RTRIM(LOWER(@action))) NOT IN ('approve', 'reject')
        BEGIN
            RAISERROR('Invalid action. Must be ''approve'' or ''reject''.', 16, 1);
            RETURN;
        END
        SET @action = LOWER(LTRIM(RTRIM(@action)));

        IF @approval_stages IS NULL OR ISJSON(@approval_stages) = 0
        BEGIN
            RAISERROR('Invalid or missing approval_stages in JSON', 16, 1);
            RETURN;
        END

        IF @approved_by IS NULL OR LTRIM(RTRIM(@approved_by)) = ''
        BEGIN
            RAISERROR('Approver EC number is required.', 16, 1);
            RETURN;
        END

        IF NOT EXISTS (SELECT 1 FROM dbo.service_po_cycle WHERE cycle_sno = @cycle_sno AND status = 'PENDING_APPROVAL')
        BEGIN
            RAISERROR('Service PO cycle not found or not awaiting approval.', 16, 1);
            RETURN;
        END

        BEGIN TRANSACTION;

        CREATE TABLE #po_approval_stages (
            seq_no INT, approver_ecno VARCHAR(30), stage VARCHAR(100),
            required_approvals VARCHAR(10), is_mandatory CHAR(1), escalation_hours VARCHAR(10),
            approver_condition VARCHAR(200), next_approver_ecno VARCHAR(30),
            can_forward CHAR(1), can_backward CHAR(1), can_edit_data CHAR(1)
        );

        INSERT INTO #po_approval_stages (
            seq_no, approver_ecno, stage, required_approvals, is_mandatory,
            escalation_hours, approver_condition, next_approver_ecno,
            can_forward, can_backward, can_edit_data
        )
        SELECT
            CAST(ojBase.[key] AS INT),
            JSON_VALUE(ojBase.[value], '$.approver_ecno'),
            JSON_VALUE(ojBase.[value], '$.stage'),
            JSON_VALUE(ojBase.[value], '$.required_approvals'),
            JSON_VALUE(ojBase.[value], '$.is_mandatory'),
            JSON_VALUE(ojBase.[value], '$.escalation_hours'),
            JSON_VALUE(ojBase.[value], '$.approver_condition'),
            JSON_VALUE(ojBase.[value], '$.next_approver_ecno'),
            JSON_VALUE(ojBase.[value], '$.can_forward'),
            JSON_VALUE(ojBase.[value], '$.can_backward'),
            JSON_VALUE(ojBase.[value], '$.can_edit_data')
        FROM OPENJSON(@approval_stages) AS ojBase;

        IF @action = 'reject'
        BEGIN
            INSERT INTO dbo.service_po_cycle_history (cycle_sno, action_type, status_by, comment)
            VALUES (@cycle_sno, 'REJECTED', @approved_by, @comments);

            UPDATE dbo.service_po_cycle SET status = 'REJECTED', current_approver_id = NULL WHERE cycle_sno = @cycle_sno;

            DROP TABLE #po_approval_stages;
            COMMIT TRANSACTION;
            SELECT 'REJECTED' AS result, @cycle_sno AS cycle_sno, @approved_by AS rejected_by, GETDATE() AS rejected_on;
            RETURN;
        END

        DECLARE @next_current_approver VARCHAR(30);
        SELECT @next_current_approver = next_stage.approver_ecno
        FROM (
            SELECT approver_ecno, LEAD(approver_ecno, 1, NULL) OVER (ORDER BY seq_no) AS next_approver_ecno
            FROM #po_approval_stages
        ) current_stage
        LEFT JOIN #po_approval_stages next_stage ON next_stage.approver_ecno = current_stage.next_approver_ecno
        WHERE current_stage.approver_ecno = @approved_by;

        INSERT INTO dbo.service_po_cycle_history (cycle_sno, action_type, status_by, comment)
        VALUES (@cycle_sno, 'APPROVED', @approved_by, @comments);

        UPDATE dbo.service_po_cycle SET current_approver_id = @next_current_approver WHERE cycle_sno = @cycle_sno;

        DECLARE @out_po_basic_sno INT = NULL, @out_po_no VARCHAR(50) = NULL, @po_details_json NVARCHAR(MAX) = NULL;

        IF @next_current_approver IS NULL
        BEGIN
            -- ── Final stage: raise ONE PO PER SUPPLIER in the cycle's split (sql/88) ──
            DECLARE @agreement_sno INT, @pr_basic_sno INT, @qty DECIMAL(18,4),
                    @discount_pct DECIMAL(5,2), @gst_pct DECIMAL(5,2),
                    @com_sno INT, @div_sno INT, @brn_sno INT, @dept_sno INT,
                    @service_sno INT, @service_name NVARCHAR(150), @rate_uom_sno INT, @agreement_no VARCHAR(30),
                    @service_type_sno INT, @period_end DATE;

            SELECT @agreement_sno = spc.agreement_sno, @pr_basic_sno = spc.pr_basic_sno, @qty = spc.qty,
                   @discount_pct = ISNULL(spc.discount_pct, 0), @gst_pct = ISNULL(spc.gst_pct, 0),
                   @com_sno = spc.com_sno, @div_sno = spc.div_sno, @brn_sno = spc.brn_sno, @dept_sno = spc.dept_sno
            FROM dbo.service_po_cycle spc
            WHERE spc.cycle_sno = @cycle_sno;

            SELECT @service_sno = sa.service_sno, @rate_uom_sno = sa.rate_uom_sno,
                   @agreement_no = sa.agreement_no, @period_end = sa.period_end_date,
                   @service_name = sm.service_name, @service_type_sno = sm.service_type_sno
            FROM dbo.service_agreement sa
            JOIN dbo.service_master sm ON sm.service_sno = sa.service_sno
            WHERE sa.agreement_sno = @agreement_sno;

            -- Defensive: a cycle with no split rows (none should exist after sql/88's
            -- backfill) falls back to the agreement's primary supplier at 100%.
            IF NOT EXISTS (SELECT 1 FROM dbo.service_po_cycle_vendor WHERE cycle_sno = @cycle_sno)
                INSERT INTO dbo.service_po_cycle_vendor (cycle_sno, vendor_sno, share_pct, rate_amount, net_cost)
                SELECT spc.cycle_sno, sa.vendor_sno, 100, spc.rate_amount, spc.net_cost
                FROM dbo.service_po_cycle spc
                JOIN dbo.service_agreement sa ON sa.agreement_sno = spc.agreement_sno
                WHERE spc.cycle_sno = @cycle_sno;

            DECLARE @supplier_count INT = (SELECT COUNT(*) FROM dbo.service_po_cycle_vendor WHERE cycle_sno = @cycle_sno);
            DECLARE @po_list VARCHAR(500) = '';
            DECLARE @cv_sno INT, @cv_vendor INT, @cv_rate DECIMAL(18,2), @cv_net DECIMAL(18,2), @cv_pct DECIMAL(9,6);
            DECLARE @new_po_sno INT, @new_po_no VARCHAR(50), @po_seq INT;
            DECLARE @po_year VARCHAR(4) = CAST(YEAR(GETDATE()) AS VARCHAR(4));

            DECLARE po_cur CURSOR LOCAL FAST_FORWARD FOR
                SELECT cycle_vendor_sno, vendor_sno, rate_amount, net_cost, share_pct
                FROM dbo.service_po_cycle_vendor
                WHERE cycle_sno = @cycle_sno
                ORDER BY cycle_vendor_sno;

            OPEN po_cur;
            FETCH NEXT FROM po_cur INTO @cv_sno, @cv_vendor, @cv_rate, @cv_net, @cv_pct;
            WHILE @@FETCH_STATUS = 0
            BEGIN
                SELECT @po_seq = ISNULL(MAX(TRY_CAST(RIGHT(po_df_no, 4) AS INT)), 0) + 1
                FROM dbo.po_request_info WITH (UPDLOCK, HOLDLOCK)
                WHERE po_df_no LIKE 'SVO-' + @po_year + '-%';
                SET @new_po_no = 'SVO-' + @po_year + '-' + RIGHT('0000' + CAST(@po_seq AS VARCHAR(4)), 4);

                INSERT INTO dbo.po_request_info (
                    vendor_sno, brn_sno, dept_sno, com_sno, div_sno, budget_sno, budget_code, pr_basic_sno,
                    po_date, required_date, purpose, terms_conditions, delivery_address,
                    is_active, workflow_types_id, current_approver_id, status, po_df_no, service_type_sno
                )
                VALUES (
                    @cv_vendor, @brn_sno, @dept_sno, @com_sno, @div_sno, NULL, NULL, @pr_basic_sno,
                    CAST(GETDATE() AS DATE), @period_end,
                    N'Recurring service PO — Agreement ' + @agreement_no + N' (' + @service_name + N')'
                        + CASE WHEN @supplier_count > 1
                               THEN N' — ' + CONVERT(NVARCHAR(12), CAST(@cv_pct AS DECIMAL(9,2))) + N'% share'
                               ELSE N'' END,
                    NULL, NULL,
                    'Y', NULL, NULL, 'A', @new_po_no, @service_type_sno
                );
                SET @new_po_sno = SCOPE_IDENTITY();

                INSERT INTO dbo.po_item_details (
                    po_basic_sno, pr_item_sno, service_sno, prod_name, specification,
                    qty, unit, unit_name, agreed_unit_price, total_cost, discount_pct, tax_pct, net_cost,
                    remarks, po_section, created_by, created_date, is_active
                )
                SELECT
                    @new_po_sno, NULL, @service_sno, sm.service_name, '',
                    @qty, @rate_uom_sno, um.uom_name, @cv_rate, @cv_rate * @qty, @discount_pct, @gst_pct, @cv_net,
                    NULL, 'SERVICE', @approved_by, GETDATE(), '1'
                FROM dbo.service_master sm
                LEFT JOIN dbo.uom_master um ON um.uom_sno = @rate_uom_sno
                WHERE sm.service_sno = @service_sno;

                INSERT INTO dbo.po_history_data (po_basic_sno, action_type, status_by, comment, is_active)
                VALUES (@new_po_sno, 'APPROVED_ISSUED', @approved_by, N'Issued after Service PO cycle approval (Agreement ' + @agreement_no + N').', 'Y');

                UPDATE dbo.service_po_cycle_vendor SET po_basic_sno = @new_po_sno WHERE cycle_vendor_sno = @cv_sno;

                -- The first PO is the "primary" one kept on the cycle / recurring log
                IF @out_po_basic_sno IS NULL
                BEGIN
                    SET @out_po_basic_sno = @new_po_sno;
                    SET @out_po_no = @new_po_no;
                END
                SET @po_list = @po_list + CASE WHEN @po_list = '' THEN '' ELSE ',' END + CAST(@new_po_sno AS VARCHAR(20));

                FETCH NEXT FROM po_cur INTO @cv_sno, @cv_vendor, @cv_rate, @cv_net, @cv_pct;
            END
            CLOSE po_cur;
            DEALLOCATE po_cur;

            UPDATE dbo.service_po_cycle SET status = 'GENERATED', po_basic_sno = @out_po_basic_sno WHERE cycle_sno = @cycle_sno;

            UPDATE dbo.service_agreement_recurring_pr_log
            SET po_basic_sno = @out_po_basic_sno, po_no = @out_po_no
            WHERE agreement_sno = @agreement_sno AND pr_basic_sno = @pr_basic_sno;

            -- One PDF-ready object per PO raised this cycle (usually one, or one
            -- per supplier on a split cycle) — same po_header/vendor/po_items
            -- shape sp_nt_ApproveSupplierQuotation returns, so the frontend can
            -- reuse the regular Purchase Order's PDF renderer unchanged.
            SET @po_details_json = (
                SELECT
                    po.po_basic_sno,
                    JSON_QUERY((
                        SELECT po.po_basic_sno, po.po_df_no,
                               CONVERT(VARCHAR(23), po.po_date, 126) AS po_date,
                               po.terms_conditions,
                               vadr.com_sno, vadr.com_name, ISNULL(vadr.logo, '') AS com_logo,
                               vadr.company_address, vadr.branch_address,
                               vadr.brn_name, vadr.dept_name
                        FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
                    )) AS po_header,
                    JSON_QUERY((
                        SELECT k.kyc_basic_info_sno AS vendor_sno, k.company_name AS vendor_name,
                               k.kyc_address AS vendor_address, k.gst_no
                        FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
                    )) AS vendor,
                    JSON_QUERY((
                        SELECT pid.prod_name, pid.specification, pid.qty, pid.unit AS uom_sno,
                               um.uom_name, pid.agreed_unit_price, pid.discount_pct, pid.tax_pct,
                               pid.total_cost, pid.net_cost
                        FROM dbo.po_item_details pid
                        LEFT JOIN dbo.uom_master um ON um.uom_sno = pid.unit
                        WHERE pid.po_basic_sno = po.po_basic_sno AND pid.is_active = 1
                        FOR JSON PATH
                    )) AS po_items
                FROM dbo.po_request_info po
                INNER JOIN dbo.vw_ActiveDeptRecords vadr
                    ON vadr.brn_sno = po.brn_sno AND vadr.dept_sno = po.dept_sno
                LEFT JOIN dbo.vw_get_all_kyc_info k ON k.kyc_basic_info_sno = po.vendor_sno
                WHERE po.po_basic_sno IN (SELECT TRY_CAST(value AS INT) FROM STRING_SPLIT(@po_list, ','))
                FOR JSON PATH
            );
        END

        DROP TABLE #po_approval_stages;
        COMMIT TRANSACTION;

        SELECT
            'SUCCESS' AS result, @cycle_sno AS cycle_sno, @approved_by AS approved_by, GETDATE() AS approved_on,
            ISNULL(@next_current_approver, 'FINAL_STAGE') AS next_approver,
            @out_po_basic_sno AS po_basic_sno, @out_po_no AS po_no,
            @po_list AS po_basic_snos, @supplier_count AS po_count,
            @po_details_json AS po_details;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        IF OBJECT_ID('tempdb..#po_approval_stages') IS NOT NULL DROP TABLE #po_approval_stages;
        SELECT 'ERROR' AS result, ERROR_NUMBER() AS error_number, ERROR_MESSAGE() AS error_message;
    END CATCH
END;
GO
